// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelFeature(arg1, arg2) {
  return window['go']['main']['App']['CancelFeature'](arg1, arg2);
}

export function CreateAgent(arg1) {
  return window['go']['main']['App']['CreateAgent'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDiff'](arg1, arg2, arg3);
}

export function GetDiscovery(arg1) {
  return window['go']['main']['App']['GetDiscovery'](arg1);
}

export function GetFeature(arg1) {
  return window['go']['main']['App']['GetFeature'](arg1);
}

export function GetFeatures() {
  return window['go']['main']['App']['GetFeatures']();
}

export function GetMockups(arg1) {
  return window['go']['main']['App']['GetMockups'](arg1);
}

export function GetPlan(arg1) {
  return window['go']['main']['App']['GetPlan'](arg1);
}

export function GetProjectRoot() {
  return window['go']['main']['App']['GetProjectRoot']();
}

export function GetRecentProjectRoots() {
  return window['go']['main']['App']['GetRecentProjectRoots']();
}

export function GetReview(arg1) {
  return window['go']['main']['App']['GetReview'](arg1);
}

export function GetStep(arg1, arg2) {
  return window['go']['main']['App']['GetStep'](arg1, arg2);
}

export function GetSteps(arg1) {
  return window['go']['main']['App']['GetSteps'](arg1);
}

export function GetUxDesign(arg1) {
  return window['go']['main']['App']['GetUxDesign'](arg1);
}

export function InstallSkills() {
  return window['go']['main']['App']['InstallSkills']();
}

export function MarkFileViewed(arg1, arg2, arg3) {
  return window['go']['main']['App']['MarkFileViewed'](arg1, arg2, arg3);
}

export function MergeAgents(arg1, arg2) {
  return window['go']['main']['App']['MergeAgents'](arg1, arg2);
}

export function OpenMockup(arg1, arg2) {
  return window['go']['main']['App']['OpenMockup'](arg1, arg2);
}

export function SaveAgent(arg1) {
  return window['go']['main']['App']['SaveAgent'](arg1);
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2);
}

export function SelectProjectRoot() {
  return window['go']['main']['App']['SelectProjectRoot']();
}

export function SkillsInstalled() {
  return window['go']['main']['App']['SkillsInstalled']();
}

export function SwitchProjectRoot(arg1) {
  return window['go']['main']['App']['SwitchProjectRoot'](arg1);
}

export function UnmarkFileViewed(arg1, arg2, arg3) {
  return window['go']['main']['App']['UnmarkFileViewed'](arg1, arg2, arg3);
}
