// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agents} from '../models';
import {git} from '../models';
import {artifacts} from '../models';

export function CancelFeature(arg1:string,arg2:boolean):Promise<void>;

export function CreateAgent(arg1:agents.Agent):Promise<void>;

export function DeleteAgent(arg1:string):Promise<void>;

export function GetAgent(arg1:string):Promise<agents.Agent>;

export function GetAgents():Promise<Array<agents.Agent>>;

export function GetDiff(arg1:string,arg2:number,arg3:string):Promise<git.FileDiff>;

export function GetDiscovery(arg1:string):Promise<string>;

export function GetFeature(arg1:string):Promise<artifacts.Feature>;

export function GetFeatures():Promise<Array<artifacts.Feature>>;

export function GetMockups(arg1:string):Promise<Array<string>>;

export function GetPlan(arg1:string):Promise<string>;

export function GetProjectRoot():Promise<string>;

export function GetRecentProjectRoots():Promise<Array<string>>;

export function GetReview(arg1:string):Promise<artifacts.Review>;

export function GetStep(arg1:string,arg2:number):Promise<artifacts.Step>;

export function GetSteps(arg1:string):Promise<Array<artifacts.Step>>;

export function GetUxDesign(arg1:string):Promise<string>;

export function InstallSkills():Promise<void>;

export function MarkFileViewed(arg1:string,arg2:number,arg3:string):Promise<void>;

export function MergeAgents(arg1:string,arg2:string):Promise<void>;

export function OpenMockup(arg1:string,arg2:string):Promise<void>;

export function SaveAgent(arg1:agents.Agent):Promise<void>;

export function SaveFileContent(arg1:string,arg2:string):Promise<void>;

export function SelectProjectRoot():Promise<string>;

export function SkillsInstalled():Promise<boolean>;

export function SwitchProjectRoot(arg1:string):Promise<void>;

export function UnmarkFileViewed(arg1:string,arg2:number,arg3:string):Promise<void>;
